from ScraperFC.FBRef import FBRef
from ScraperFC.FiveThirtyEight import FiveThirtyEight
from ScraperFC.ScraperFC import ScraperFC
from ScraperFC.Understat import Understat
from ScraperFC.SofaScore import SofaScore
from ScraperFC.ClubElo import ClubElo
from ScraperFC.Capology import Capology
from ScraperFC.Transfermarkt import Transfermarkt
from ScraperFC.shared_functions import *